apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: rhacs-image-scan
spec:
  description: >-
    Scan an image with Red Hat Advanced Cluster Security.

    This task allows you to return full vulnerability scan results for an image
    in CSV, Table, or JSON formats. The companion rhacs-image-check task checks
    an image against build-time policies.
  params:
    - default: rox-central-endpoint
      description: >-
        Name of secret containing the address:port tuple for RHACS Stackrox
        Central.
      name: rox_central_endpoint
      type: string
    - default: rox-api-token
      description: >-
        Name of secret containing the RHACS StackRox API token with CI
        permissions.
      name: rox_api_token
      type: string
    - default: >-
        registry.test.lab.local:5000/quay.io/stackrox-io/roxctl@sha256:1b3424b9e385de7b0fa6f3b49734081840af31edbdcb2f36c0d9260e84896856
      description: Image providing the roxctl tool.
      name: rox_image
      type: string
    - default: $(params.IMAGE)
      description: >
        Full name of image to scan.


        SHA 256 digest may be included to ensure scan of sequental runs with
        same tag.

        Examples: 'gcr.io/rox/sample:5.0-rc1', '$(params.IMAGE)',
        '$(params.IMAGE)@$(tasks.buildah.results.IMAGE_DIGEST)'
      name: image
      type: string
    - default: json
      description: Results output format (json | csv | table)
      name: output_format
      type: string
    - default: 'false'
      description: >
        Do not verify TLS certificates.


        When set to "true", skip verifying the TLS certs of the Central endpoint
        and registry.
      name: insecure-skip-tls-verify
      type: string
  steps:
    - args:
        - image
        - scan
        - '--endpoint=$(ROX_CENTRAL_ENDPOINT)'
        - '--insecure-skip-tls-verify=$(INSECURE)'
        - '--output=$(OUTPUT)'
        - '--image=$(IMAGE)'
      env:
        - name: HOME
          value: /tekton/home
        - name: IMAGE
          value: $(params.image)
        - name: INSECURE
          value: $(params.insecure-skip-tls-verify)
        - name: OUTPUT
          value: $(params.output_format)
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: rox_api_token
              name: $(params.rox_api_token)
        - name: ROX_CENTRAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: rox_central_endpoint
              name: $(params.rox_central_endpoint)
      image: $(params.rox_image)
      name: rox-image-scan
      resources: {}
