---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-webhook
  annotations:
      argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: "Service"
    name: el-webhook
    weight: 100