---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
  annotations:
      argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountName: pipeline
  triggers:
    - name: gitlab-webhook
      interceptors:
        - name: "verify-gitlab-payload"
          ref: 
            name: "gitlab"
            kind: "ClusterInterceptor"
          params:
            - name: secretRef
              value:
                secretName: "gitlab-secret"
                secretKey: "secretToken"
            - name: eventTypes
              value:
                - "Push Hook"
      bindings:
        - ref: gitlab-triggerbinding
      template:
        ref: gohello-trigger-template