---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-triggerbinding
  annotations:
      argocd.argoproj.io/sync-wave: "0"
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: gitshortsha
    value: $(extensions.truncated_sha)
  - name: gitbranchname
    value: $(extensions.truncated_sha)
  - name: gitrepositoryurl
    value: $(body.repository.git_http_url)
  - name: contenttype
    value: $(header.Content-Type)