---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-triggerbinding
  annotations:
      argocd.argoproj.io/sync-wave: "0"
spec:
  params:
  - name: revision
    value: $(body.after)
  - name: sha
    value: $(body.extensions.truncated_sha)
  - name: ranchname
    value: $(body.extensions.branchname)
  - name: gitrepositoryurl
    value: $(body.repository.git_http_url)
  - name: contenttype
    value: $(header.Content-Type)

  #- name: gitrevision
  #  value: $(body.after)
  #- name: gitshortsha
  #  value: $(body.extensions.truncated_sha)
  #- name: gitbranchname
  #  value: $(body.extensions.branchname)
  #- name: gitrepositoryurl
  #  value: $(body.repository.git_http_url)
  #- name: contenttype
  #  value: $(header.Content-Type)