---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gohello-trigger-template
  annotations:
      argocd.argoproj.io/sync-wave: "0"
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitshortsha
    description: The short commit sha
    default: master
  - name: gitbranchname
    description: The branch name
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: gohello-build-
      # name: gohello-dev-$(tt.params.gitbranchname)-$(tt.params.gitshortsha)
      labels:
        tekton.dev/pipeline: gohello-build-pipeline
    spec:
      pipelineRef:
        name: gohello-build-pipeline
      params:
        - name: GIT_REPO
          value: $(tt.params.gitrepositoryurl)
        - name: GIT_REVISION
          value: $(tt.params.gitbranchname)
        - name: APP_IMAGE_TAG
          value: $(tt.params.gitbranchname)-$(tt.params.gitshortsha)
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi