apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-customisations
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: console-customisations/
    repoURL: 'http://192.168.88.1:7010/root/gitops-cluster-mgmt.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
