apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-hello-helm-app-dev
spec:
  destination:
    namespace: 'go-hello-dev'
    server: 'https://kubernetes.default.svc'
  source:
        path: k8s/helms/gohello
        repoURL: 'http://192.168.88.1:7010/root/gohello-config.git'
        targetRevision: 'main'
        helm:
          valueFiles:
            - 'values-dev.yaml'
          values: |
            targetNamespace: 'go-hello-dev'
  project: project-gohello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true