apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-hello-app-set
spec:
  generators:
  - list:
      elements:
      - environment: dev
        cluster: 'https://kubernetes.default.svc'
        repoURL: 'http://192.168.88.1:7010/root/hello.git'
        branch: 'main'
        valuesFile: 'values-dev.yaml'
        targetNamespace: 'go-hello-dev'
      - environment: prod
        cluster: 'https://kubernetes.default.svc'
        repoURL: 'http://192.168.88.1:7010/root/hello.git'
        branch: 'main'
        valuesFile: 'values-prod.yaml'
        targetNamespace: 'go-hello-prod'
  template:
    metadata:
      name: 'go-hello-helm-app-{{environment}}'
    spec:      
      destination:
        namespace: '{{targetNamespace}}'
        server: '{{cluster}}'
      source:
        path: k8s/helms/gohello
        repoURL: '{{repoURL}}'
        targetRevision: '{{branch}}'
        helm:
          valueFiles:
            - '{{valuesFile}}'
          values: |
            targetNamespace: {{targetNamespace}}
      project: project-gohello
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
          - Replace=false
        automated:
          prune: true
          selfHeal: true