apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limit
  namespace: for-replacement
spec:
  limits:
  - default:
      ephemeral-storage: 10Gi
    defaultRequest:
      ephemeral-storage: 1Gi 
    type: Container