kind: Secret
apiVersion: v1
metadata:
  name: quay
  namespace: for-replacement
  annotations:
      argocd.argoproj.io/sync-wave: "0"
      kubernetes.io/service-account.name: default
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJxdWF5LmFwcHMudGVzdC5sYWIubG9jYWwiOnsidXNlcm5hbWUiOiJwYWNvIiwicGFzc3dvcmQiOiIxcWF6QFdTWCIsImF1dGgiOiJjR0ZqYnpveGNXRjZRRmRUV0E9PSIsImVtYWlsIjoiIn19fQ==
type: kubernetes.io/dockerconfigjson
