kind: Secret
apiVersion: v1
metadata:
  name: quay
  namespace: for-replacement
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJxdWF5LmFwcHMudGVzdC5sYWIubG9jYWwiOnsidXNlcm5hbWUiOiJwYWNvIiwicGFzc3dvcmQiOiIxcWF6QFdTWCIsImF1dGgiOiJjR0ZqYnpveGNXRjZRRmRUV0E9PSIsImVtYWlsIjoiIn19fQ==
type: kubernetes.io/dockerconfigjson
