apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gohello-editors
  namespace: for-replacement
  annotations:
    # Ensures that this resource will be applied after the namespace
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  # The role being bound. In this case we're re-using the existing
  # edit role that's defined at cluster scope
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  # Make user "foo" a subject of this role, thus granting
  # them edit access in the project-memes-dev namespace
  - kind: User
    name: for-replacement
    namespace: for-replacement