apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-hello-dev
bases:
- ../../base

resources:
- ./pipeline/*

# Patches are edits to make to a set of one or more targets
patches:
# This patch targets the Namespace resource and changes the
# value of metadata.name to "go-hello-dev"
- target:
    kind: Namespace
    name: for-replacement
  patch: |-
    - op: replace
      path: /metadata/name
      value: go-hello-dev

- target:
    kind: RoleBinding
    name: gohello-editors
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: user2
    - op: replace
      path: /subjects/0/namespace
      value: go-hello-dev
#    - op: replace
#      path: /metadata/namespace
#      value: go-hello-dev


#- target:
#    kind: ServiceAccount
#    name: default
#  patch: |-
#    - op: replace
#      path: /imagePullSecrets/1/name/
#      value: quay