apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gohello-build-pipeline
spec:
  params:
    - default: go-pipeline-hello
      name: APP_NAME
      type: string
    - default: 'http://192.168.88.1:7010/root/hello.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: quay.apps.test.lab.local/dev/gohello
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: 1.17.12-2-ubi7
      name: VERSION
      type: string
    - default: 'http://192.168.88.1:7010/root/hello.git'
      name: GIT_CONFIG_REPO
      type: string
    - default: v1.0.1
      name: APP_IMAGE_TAG
      type: string
    - default: k8s/helms/gohello/values-dev.yaml
      name: KUSTOMIZATION_PATH
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: '$(params.IMAGE_NAME):$(params.APP_IMAGE_TAG)'
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-go
      workspaces:
        - name: source
          workspace: workspace
    - name: git-update-deployment
      params:
        - name: GIT_REPOSITORY
          value: $(params.GIT_CONFIG_REPO)
        - name: CURRENT_IMAGE
          value: $(params.IMAGE_NAME)
        - name: NEW_IMAGE
          value: $(params.IMAGE_NAME)
        - name: NEW_DIGEST
          value: $(params.APP_IMAGE_TAG)
        - name: KUSTOMIZATION_PATH
          value: $(params.KUSTOMIZATION_PATH)
      runAfter:
        - build
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace